const test = require('node:test')
const assert = require('node:assert/strict')

const { IPC } = require('../../src/shared/ipc-channels')

test('shared IPC contract exports stable frozen channel names', () => {
  assert.equal(IPC.PET_PACKS_SET_ACTIVE, 'pet-packs:set-active')
  assert.equal(IPC.PET_SHOW_CONTEXT_MENU, 'pet:show-context-menu')
  assert.equal(IPC.PET_MENU_COMMAND, 'pet:menu-command')
  assert.equal(IPC.PET_REQUEST_FOCUS_FOR_CURSOR, 'pet:request-focus-for-cursor')
  assert.equal(IPC.PET_CHAT_OPEN, 'pet-chat:open')
  assert.equal(IPC.PET_CHAT_GET_STATE, 'pet-chat:get-state')
  assert.equal(IPC.PET_CHAT_SET_ALWAYS_ON_TOP, 'pet-chat:set-always-on-top')
  assert.equal(IPC.PET_CHAT_SEND_MESSAGE, 'pet-chat:send-message')
  assert.equal(IPC.AI_GENERATE_PERSONA_DRAFT, 'ai:generate-persona-draft')
  assert.equal(IPC.AI_GET_MEMORY_PROFILE, 'ai:get-memory-profile')
  assert.equal(IPC.AI_DELETE_MEMORY, 'ai:delete-memory')
  assert.equal(IPC.AI_CLEAR_PET_PACK_MEMORIES, 'ai:clear-pet-pack-memories')
  assert.equal(IPC.CATALOG_INSTALL_SELECTION, 'catalog:install-selection')
  assert.equal(IPC.SETTINGS_OPEN, 'settings:open')
  assert.equal(Object.isFrozen(IPC), true)
})
