import type { PluginViewState } from '../../../shared/openpet-contracts'
import { PluginEntryDetails } from '../components/PluginEntryDetails'
import { Toggle } from '../components/Toggle'
import { formatBytes } from '../lib/format'
import type { PluginsPaneProps } from './PluginsPaneTypes'

export function PluginRow({ plugin, ...props }: PluginsPaneProps & { plugin: PluginViewState }) {
  const blocked = Boolean(plugin.blockStatus?.blocked)
  const canRun = plugin.enabled && !blocked && (!plugin.requiresNativeExecution || plugin.nativeExecutionApproved)
  const services = plugin.entries?.services || []
  const summary = [
    `${(plugin.permissions || []).length} 项权限`, plugin.commands?.length ? `${plugin.commands.length} 个命令` : '',
    plugin.entries?.setup?.length ? `${plugin.entries.setup.length} 个 Setup` : '', services.length ? `${services.length} 个服务` : ''
  ].filter(Boolean)
  return <article className={blocked ? 'plugin-row blocked' : 'plugin-row'}>
    <div className="plugin-card-header"><div className="plugin-title-block"><div className="plugin-title"><strong>{plugin.name}</strong><span className="plugin-source-badge">{plugin.source}</span></div><div className="plugin-meta"><span>{plugin.id}</span><span>v{plugin.version}</span><span>{plugin.signatureStatus?.label || 'Signature unknown'}</span></div></div><div className="plugin-enable-control"><span>{plugin.enabled ? '已启用' : '已停用'}</span><Toggle ariaLabel={`Enable ${plugin.name}`} checked={plugin.enabled} onChange={(value) => props.onToggle(plugin.id, value)} /></div></div>
    <div className="plugin-summary-strip"><span className={plugin.enabled ? 'plugin-status-pill success' : 'plugin-status-pill'}>{plugin.enabled ? '插件已启用' : '当前停用'}</span><span className={blocked ? 'plugin-status-pill danger' : 'plugin-status-pill'}>{blocked ? '已被策略阻止' : services.some((service) => service.runtime?.status === 'running') ? '服务运行中' : plugin.runnable ? '可运行' : '仅展示'}</span>{summary.map((item) => <span className="plugin-summary-item" key={item}>{item}</span>)}</div>
    <div className="plugin-main">{plugin.requiresNativeExecution ? <div className="plugin-native-execution"><label className="plugin-health-policy-toggle"><span>允许原生进程执行</span><Toggle ariaLabel={`Allow native process execution for ${plugin.name}`} checked={Boolean(plugin.nativeExecutionApproved)} disabled={blocked} onChange={(value) => props.onSetNativeExecutionApproved(plugin.id, value)} /></label></div> : null}
      {plugin.id === 'openpet.creator-studio' ? <div className="plugin-config-panel plugin-primary-workflow"><div className="plugin-config-header"><strong>生成并等待复查</strong><button type="button" className="ghost" disabled={!canRun || Boolean(props.openingDashboard)} onClick={() => props.onOpenDashboard(plugin.id, 'main')}>查看任务详情</button></div><label className="plugin-config-field"><span>Creator Studio 请求</span><textarea className="text-input" value={props.creatorStudioPromptDraft} onChange={(event) => props.onChangeCreatorStudioPromptDraft(event.target.value)} /></label><button type="button" className="primary" disabled={!canRun || props.runningCreatorStudioDefaultFlow} onClick={props.onRunCreatorStudioDefaultFlow}>{props.runningCreatorStudioDefaultFlow ? '处理中' : '开始生成'}</button></div> : null}
      {plugin.id === 'openpet.agent-awareness' ? <div className="plugin-quick-entry"><strong>Codex Awareness</strong><button type="button" className="ghost" disabled={!canRun} onClick={() => props.onOpenDashboard(plugin.id, 'main', { query: { view: 'details' } })}>查看 Codex 详情</button></div> : null}
      <details className="plugin-management-disclosure"><summary><span className="plugin-disclosure-summary-copy"><strong>管理与诊断</strong><span>{summary.join(' · ') || '查看插件详细信息'}</span></span></summary><div className="plugin-management-body">
        <div className="permission-line"><strong>权限</strong><span>{plugin.permissions?.length ? plugin.permissions.join(' · ') : '无权限'}</span></div><div className="plugin-storage-line"><span>{plugin.storage?.valid === false ? '存储数据无效' : `存储 ${plugin.storage?.keyCount || 0} 项 / ${formatBytes(plugin.storage?.byteSize || 0)}`}</span><button type="button" className="ghost" disabled={props.clearingStorage === plugin.id} onClick={() => props.onClearStorage(plugin.id)}>{props.clearingStorage === plugin.id ? '清理中' : '清理存储'}</button></div>
        {plugin.commands?.length ? <><input className="text-input" value={props.commandPayloadDrafts[plugin.id] || ''} placeholder='{"runId":"..."}' onChange={(event) => props.onChangeCommandPayload(plugin.id, event.target.value)} /> <div className="plugin-commands">{plugin.commands.map((command) => <button type="button" className="ghost" key={command.id} disabled={!canRun || props.runningCommand === `${plugin.id}:${command.id}`} onClick={() => props.onRun(plugin.id, command.id)}>{props.runningCommand === `${plugin.id}:${command.id}` ? '运行中' : command.title}</button>)}</div></> : null}
        {plugin.entries?.setup?.map((setup) => <div className="plugin-service-control" key={setup.id}><span>Setup status: {setup.runtime?.status || 'not-run'}</span><button type="button" className="ghost" disabled={!canRun || props.runningSetup === `${plugin.id}:${setup.id}`} onClick={() => props.onRunSetup(plugin.id, setup.id)}>Run {setup.title || setup.id} Setup</button></div>)}
        {services.map((service) => <div className="plugin-service-control" key={service.id}><span>Service status: {service.runtime?.status || 'stopped'}</span><button type="button" className="ghost" disabled={!canRun || props.changingService === `${plugin.id}:${service.id}`} onClick={() => service.runtime?.status === 'running' ? props.onStopService(plugin.id, service.id) : props.onStartService(plugin.id, service.id)}>{service.runtime?.status === 'running' ? 'Stop' : 'Start'} {service.title || service.id}</button><button type="button" className="ghost" disabled={!plugin.enabled || !service.health?.url} onClick={() => props.onCheckServiceHealth(plugin.id, service.id)}>Check health</button></div>)}
        <PluginEntryDetails source={plugin} compact />{plugin.source === 'local' ? <button type="button" className="danger-text" onClick={() => props.onUninstallPlugin(plugin.id)}>{props.uninstallingPlugin === plugin.id ? '卸载中' : '卸载插件'}</button> : null}
      </div></details>
    </div>
  </article>
}
