import type { PluginsPaneProps } from './PluginsPaneTypes'
import { formatPluginLogLevel, formatPluginLogTime, getPluginLogLevelClass } from '../lib/format'

export function PluginLogs({ logs, logsPage, filters, plugins, onChangeFilters, onExportLogs, onClearLogs, onPrevLogsPage, onNextLogsPage }: PluginsPaneProps) {
  return <details className="plugin-log-disclosure"><summary><span className="plugin-disclosure-summary-copy"><strong>运行日志</strong><span>第 {logsPage.page} / {logsPage.totalPages} 页 · 共 {logsPage.total} 条</span></span></summary><div className="plugin-log-panel">
    <div className="plugin-log-header"><span>按插件、级别或关键词筛选日志</span><div className="plugin-log-actions"><button type="button" className="ghost" onClick={() => onExportLogs('json')} disabled={logs.length === 0}>JSON</button><button type="button" className="ghost" onClick={() => onExportLogs('csv')} disabled={logs.length === 0}>CSV</button><button type="button" className="ghost" onClick={onClearLogs} disabled={logs.length === 0}>清空</button></div></div>
    <div className="plugin-log-filters"><select className="text-input" value={filters.pluginId} onChange={(event) => onChangeFilters({ ...filters, pluginId: event.target.value })}><option value="">全部插件</option>{plugins.map((plugin) => <option value={plugin.id} key={plugin.id}>{plugin.name}</option>)}</select><select className="text-input" value={filters.level} onChange={(event) => onChangeFilters({ ...filters, level: event.target.value })}><option value="">全部级别</option><option value="info">Info</option><option value="warn">Warning</option><option value="error">Error</option></select><input className="text-input" value={filters.query} placeholder="搜索日志" onChange={(event) => onChangeFilters({ ...filters, query: event.target.value })} /></div>
    <div className="plugin-log-list">{logs.length === 0 ? <div className="empty-chat">暂无日志</div> : logs.map((log) => <div className={`plugin-log-row ${getPluginLogLevelClass(log.level)}`} key={log.id}><span>{formatPluginLogTime(log.timestamp)}</span><strong>{formatPluginLogLevel(log.level)}</strong><div><span>{log.pluginId || 'plugin'}</span>{log.commandId ? <span>/{log.commandId}</span> : null}</div><p>{log.message}</p></div>)}</div>
    <div className="log-pagination"><button type="button" className="ghost" onClick={onPrevLogsPage} disabled={!onPrevLogsPage}>上一页</button><span>当前 {logs.length} 条 / 每页 {logsPage.pageSize} 条</span><button type="button" className="ghost" onClick={onNextLogsPage} disabled={!onNextLogsPage}>下一页</button></div>
  </div></details>
}
