import type { PluginViewState } from '../../../shared/openpet-contracts'
import { PluginEntryDetails } from '../components/PluginEntryDetails'
import { Toggle } from '../components/Toggle'
import { formatBytes } from '../lib/format'
import type { PluginsPaneProps } from './PluginsPaneTypes'

export function PluginRow({ plugin, ...props }: PluginsPaneProps & { plugin: PluginViewState }) {
  const blocked = Boolean(plugin.blockStatus?.blocked)
  const canRun = plugin.enabled && !blocked && (!plugin.requiresNativeExecution || plugin.nativeExecutionApproved)
  const services = plugin.entries?.services || []
  const health = services.find((service) => service.runtime?.health)?.runtime?.health
  const stoppedServices = services.filter((service) => service.runtime?.status === 'stopped').length
  const failedServices = services.filter((service) => service.runtime?.status === 'failed').length
  const summary = [
    `${(plugin.permissions || []).length} 项权限`, plugin.commands?.length ? `${plugin.commands.length} 个命令` : '',
    plugin.entries?.setup?.length ? `${plugin.entries.setup.length} 个 Setup` : '', services.length ? `${services.length} 个服务` : '',
    stoppedServices ? `${stoppedServices} 个服务已停止` : '', failedServices ? `${failedServices} 个服务运行失败` : ''
  ].filter(Boolean)
  return <article className={blocked ? 'plugin-row blocked' : 'plugin-row'}>
    <div className="plugin-card-header"><div className="plugin-title-block"><div className="plugin-title"><strong>{plugin.name}</strong><span className="plugin-source-badge">{plugin.source}</span></div><div className="plugin-meta"><span>{plugin.id}</span><span>v{plugin.version}</span><span>{plugin.signatureStatus?.label || 'Signature unknown'}</span></div></div><div className="plugin-enable-control"><span>{plugin.enabled ? '已启用' : '已停用'}</span><Toggle ariaLabel={`Enable ${plugin.name}`} checked={plugin.enabled} onChange={(value) => props.onToggle(plugin.id, value)} /></div></div>
    <div className="plugin-summary-strip"><span className={plugin.enabled ? 'plugin-status-pill success' : 'plugin-status-pill'}>{plugin.enabled ? '插件已启用' : '当前停用'}</span><span className={blocked ? 'plugin-status-pill danger' : 'plugin-status-pill'}>{blocked ? '已被策略阻止' : services.some((service) => service.runtime?.status === 'running') ? '服务运行中' : plugin.runnable ? '可运行' : '仅展示'}</span>{summary.map((item) => <span className="plugin-summary-item" key={item}>{item}</span>)}</div>
    <div className="plugin-main">{plugin.requiresNativeExecution ? <div className="plugin-native-execution"><label className="plugin-health-policy-toggle"><span>允许原生进程执行</span><Toggle ariaLabel={`Allow native process execution for ${plugin.name}`} checked={Boolean(plugin.nativeExecutionApproved)} disabled={blocked} onChange={(value) => props.onSetNativeExecutionApproved(plugin.id, value)} /></label></div> : null}
      {plugin.id === 'openpet.creator-studio' ? <div className="plugin-config-panel plugin-primary-workflow"><div className="plugin-config-header"><strong>生成并等待复查</strong><button type="button" className="ghost" disabled={!canRun || Boolean(props.openingDashboard)} onClick={() => props.onOpenDashboard(plugin.id, 'main')}>查看任务详情</button></div><label className="plugin-config-field"><span>Creator Studio 请求</span><textarea className="text-input" value={props.creatorStudioPromptDraft} onChange={(event) => props.onChangeCreatorStudioPromptDraft(event.target.value)} /></label><button type="button" className="primary" disabled={!canRun || props.runningCreatorStudioDefaultFlow} onClick={props.onRunCreatorStudioDefaultFlow}>{props.runningCreatorStudioDefaultFlow ? '处理中' : '开始生成'}</button></div> : null}
      {plugin.id === 'openpet.agent-awareness' ? <div className="plugin-quick-entry"><strong>Agent Awareness 原生详情</strong>{health?.message ? <span>Health note: {health.message}</span> : null}{health?.details?.map((detail) => <span key={detail.label}>{detail.label}: {detail.value}</span>)}<button type="button" className="ghost" disabled={!canRun} onClick={() => props.onOpenDashboard(plugin.id, 'main', { query: { view: 'details' } })}>查看 Codex 详情</button></div> : null}
      <details className="plugin-management-disclosure"><summary><span className="plugin-disclosure-summary-copy"><strong>管理与诊断</strong><span>{summary.join(' · ') || '查看插件详细信息'}</span></span></summary><div className="plugin-management-body">
        <div className="permission-line"><strong>权限</strong><span>{plugin.permissions?.length ? plugin.permissions.join(' · ') : '无权限'}</span></div><div className="plugin-storage-line"><span>{plugin.storage?.valid === false ? '存储数据无效' : `存储 ${plugin.storage?.keyCount || 0} 项 / ${formatBytes(plugin.storage?.byteSize || 0)}`}</span><button type="button" className="ghost" disabled={props.clearingStorage === plugin.id} onClick={() => props.onClearStorage(plugin.id)}>{props.clearingStorage === plugin.id ? '清理中' : '清理存储'}</button></div>
        {plugin.commands?.length ? <><input className="text-input" value={props.commandPayloadDrafts[plugin.id] || ''} placeholder='{"runId":"..."}' onChange={(event) => props.onChangeCommandPayload(plugin.id, event.target.value)} /> <div className="plugin-commands">{plugin.commands.map((command) => <button type="button" className="ghost" key={command.id} disabled={!canRun || props.runningCommand === `${plugin.id}:${command.id}`} onClick={() => props.onRun(plugin.id, command.id)}>{props.runningCommand === `${plugin.id}:${command.id}` ? '运行中' : command.title}</button>)}</div></> : null}
        {props.lastCommandResult?.pluginId === plugin.id ? <div className="plugin-command-result"><strong>最近命令结果</strong><span>{props.lastCommandResult.commandId}{props.lastCommandResult.exitCode != null ? ` · exit ${props.lastCommandResult.exitCode}` : ''}</span><p>{props.lastCommandResult.message}</p>{props.lastCommandResult.details.length ? <dl className="plugin-command-details">{props.lastCommandResult.details.map((detail) => <div key={`${detail.label}:${detail.value}`}><dt>{detail.label}</dt><dd>{detail.value}</dd></div>)}</dl> : null}{props.lastCommandResult.resultText ? <code>{props.lastCommandResult.resultText}</code> : null}{props.lastCommandResult.stdout ? <p>stdout: {props.lastCommandResult.stdout}</p> : null}{props.lastCommandResult.stderr ? <p>stderr: {props.lastCommandResult.stderr}</p> : null}</div> : null}
        {plugin.entries?.setup?.map((setup) => <div className="plugin-service-control" key={setup.id}><span>Setup status: {setup.runtime?.status || 'not-run'}</span><button type="button" className="ghost" disabled={!canRun || props.runningSetup === `${plugin.id}:${setup.id}`} onClick={() => props.onRunSetup(plugin.id, setup.id)}>Run {setup.title || setup.id} Setup</button></div>)}
        {services.map((service) => <div className="plugin-service-control" key={service.id}><span>Service status: {service.runtime?.status || 'stopped'}</span><span>Health: {service.runtime?.health?.status || 'unknown'}</span><button type="button" className="ghost" disabled={!canRun || props.changingService === `${plugin.id}:${service.id}`} onClick={() => service.runtime?.status === 'running' ? props.onStopService(plugin.id, service.id) : props.onStartService(plugin.id, service.id)}>{service.runtime?.status === 'running' ? 'Stop' : 'Start'} {service.title || service.id}</button><button type="button" className="ghost" aria-label={`Check ${service.title || service.id} Health`} disabled={!plugin.enabled || !service.health?.url} onClick={() => props.onCheckServiceHealth(plugin.id, service.id)}>Check health</button>{service.health?.url ? <div className="plugin-health-policy"><label className="plugin-health-policy-toggle"><span>Periodic health</span><Toggle ariaLabel={`Enable periodic health for ${service.title || service.id}`} checked={Boolean(service.healthPolicy?.enabled)} disabled={!plugin.enabled || Boolean(props.savingServiceHealthPolicy)} onChange={(enabled) => props.onSaveServiceHealthPolicy(plugin.id, service.id, enabled, service.healthPolicy?.intervalMs || 30000)} /></label><label className="plugin-health-policy-interval"><span>Interval</span><select className="text-input" value={String(service.healthPolicy?.intervalMs || 30000)} disabled={!plugin.enabled || Boolean(props.savingServiceHealthPolicy)} onChange={(event) => props.onSaveServiceHealthPolicy(plugin.id, service.id, Boolean(service.healthPolicy?.enabled), Number(event.target.value))}><option value="30000">30000</option><option value="60000">60000</option><option value="120000">120000</option></select></label></div> : null}</div>)}
        {plugin.entries?.dashboards?.length ? <div className="plugin-commands">{plugin.entries.dashboards.map((dashboard) => { const dashboardKey = `${plugin.id}:${dashboard.id}`; const opening = props.openingDashboard === dashboardKey; return <button type="button" className="ghost" key={dashboard.id} disabled={!canRun || opening} onClick={() => props.onOpenDashboard(plugin.id, dashboard.id)}>{opening ? '打开中' : dashboard.title}</button> })}</div> : null}
        <PluginEntryDetails source={plugin} compact />{plugin.source === 'local' ? <button type="button" className="danger-text" onClick={() => props.onUninstallPlugin(plugin.id)}>{props.uninstallingPlugin === plugin.id ? '卸载中' : '卸载插件'}</button> : null}
      </div></details>
    </div>
  </article>
}
