import { controlCenterAPI as api } from '../api/control-center-api'
import { downloadTextFile } from '../lib/download'
import { ensureCreatorStudioServiceReady } from '../lib/creator-studio-dashboard'
import { messageFromError } from '../lib/errors'
import { toCommandResultPreview } from '../lib/plugin-command-result.mjs'
import { isBackendUnavailableBeforeDispatch, pluginHttpApi, shouldUseImmediatePluginCommandFallback } from '../features/plugins/api'
import type { JsonObject, JsonValue, PluginDashboardOpenOptions, PluginViewState } from '../../../shared/openpet-contracts'

const CREATOR = 'openpet.creator-studio'
const serviceStatus = (plugin: PluginViewState | null) => plugin?.entries?.services?.find((service) => service.id === 'studio')?.runtime?.status || 'stopped'
const find = (items: PluginViewState[], id: string) => items.find((item) => item.id === id) || null
const parsePayload = (draft: string): JsonObject | undefined => { if (!draft.trim()) return undefined; const parsed = JSON.parse(draft); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('命令 Payload 必须是 JSON 对象'); return parsed as JsonObject }

export function usePluginsPaneActions(data: any) {
  const { plugins, setPlugins, filters, setStatus, setBusy, setPluginReview, refreshPlugins, refreshLogs, loadLogsPage, commandPayloadDrafts, setLastCommandResult, creatorStudioPromptDraft, setCreatorStudioPromptDraft, setCreatorStudioLastRunId, imGatewayTelegramTokenDraft, setImGatewayTelegramTokenDraft } = data
  const fail = (error: unknown, fallback: string) => setStatus(messageFromError(error, fallback))
  const refresh = async () => { await Promise.allSettled([refreshPlugins(), refreshLogs()]) }
  const onToggle = async (id: string, enabled: boolean) => { try { const value = await pluginHttpApi.enable(id, enabled); setPlugins((items: PluginViewState[]) => items.map((item) => item.id === id ? { ...item, ...value } : item)); setStatus(enabled ? '插件已启用' : '插件已停用') } catch (error) { fail(error, '插件状态更新失败') }; await refresh() }
  const onSetNativeExecutionApproved = async (id: string, approved: boolean) => { try { const value = await pluginHttpApi.nativeApproval(id, approved); setPlugins((items: PluginViewState[]) => items.map((item) => item.id === id ? { ...item, ...value } : item)); setStatus(approved ? '已允许原生进程执行' : '已撤销原生进程执行') } catch (error) { fail(error, '原生执行授权更新失败') }; await refresh() }
  const onInspectPluginPackage = async () => { setBusy((state: any) => ({ ...state, inspectingPlugin: true })); try { const result = await api.inspectPluginPackage(); if (!result.canceled) setPluginReview(result) } catch (error) { fail(error, '插件包检查失败') } finally { setBusy((state: any) => ({ ...state, inspectingPlugin: false })) } }
  const onInspectGithubPluginRepository = async () => { setBusy((state: any) => ({ ...state, inspectingGithubPlugin: true })); try { const result = await pluginHttpApi.inspectGithub(data.githubRepositoryUrl); if (!result.canceled) setPluginReview(result) } catch (error) { fail(error, 'GitHub 插件导入失败') } finally { setBusy((state: any) => ({ ...state, inspectingGithubPlugin: false })) } }
  const onInstallReviewedPlugin = async () => { const review = data.pluginReview; if (!review?.selectionId) return; setBusy((state: any) => ({ ...state, installingPlugin: true })); try { review.installMode === 'update' ? await pluginHttpApi.update(review.selectionId) : await pluginHttpApi.install(review.selectionId); setPluginReview(null); setStatus(review.installMode === 'update' ? '插件已更新' : '插件已安装，默认保持停用'); await refresh() } catch (error) { fail(error, '插件安装失败') } finally { setBusy((state: any) => ({ ...state, installingPlugin: false })) } }
  const onUninstallPlugin = async (id: string) => { if (!window.confirm(`卸载插件 ${id}？`)) return; const removeStorage = window.confirm('同时删除私有存储？'); setBusy((state: any) => ({ ...state, uninstallingPlugin: id })); try { await pluginHttpApi.uninstall(id, removeStorage); setStatus('插件已卸载'); await refresh() } catch (error) { fail(error, '插件卸载失败') } finally { setBusy((state: any) => ({ ...state, uninstallingPlugin: '' })) } }
  const onSaveConfig = async (id: string) => { const plugin = find(plugins, id); if (!plugin) return; setBusy((state: any) => ({ ...state, savingConfig: id })); try { await pluginHttpApi.setConfig(id, plugin.config || {}); setStatus('插件配置已保存') } catch (error) { fail(error, '插件配置保存失败') } finally { setBusy((state: any) => ({ ...state, savingConfig: '' })); await refresh() } }
  const onRun = async (id: string, command: string) => { let args; try { args = parsePayload(commandPayloadDrafts[id] || '') } catch (error) { fail(error, '命令 Payload 无效'); return }; const key = `${id}:${command}`; setBusy((state: any) => ({ ...state, runningCommand: key })); try { let preview; const fallback = shouldUseImmediatePluginCommandFallback(import.meta.env?.DEV === true, Boolean((globalThis as any).openpetBackend)); if (fallback) preview = toCommandResultPreview(await api.runPluginCommand(id, command, args)); else { try { const job = await pluginHttpApi.command(id, command, args); preview = { pluginId: id, commandId: command, message: `任务已排队：${job.jobId}`, details: [], resultText: '', stdout: '', stderr: '', exitCode: null } } catch (error) { if (!isBackendUnavailableBeforeDispatch(error)) throw error; preview = toCommandResultPreview(await api.runPluginCommand(id, command, args)) } } setLastCommandResult(preview); setStatus(preview.message || '命令执行成功') } catch (error) { setLastCommandResult(null); fail(error, '命令运行失败') } finally { setBusy((state: any) => ({ ...state, runningCommand: '' })); await refreshLogs() } }
  const onRunCreatorStudioDefaultFlow = async () => { const plugin = find(plugins, CREATOR); if (!plugin || !plugin.enabled) return setStatus('请先启用 Creator Studio 插件'); if (!creatorStudioPromptDraft.trim()) return setStatus('请先输入 Creator Studio 请求'); setBusy((state: any) => ({ ...state, runningCreatorStudioDefaultFlow: true })); try { const result = await pluginHttpApi.creatorFlow(creatorStudioPromptDraft.trim()); setCreatorStudioLastRunId(String(result.runId || '')); setLastCommandResult(result.lastCommandResult ? toCommandResultPreview(result.lastCommandResult) : null); setStatus(result.message || '生成流程已完成'); if (['completed', 'review-required'].includes(result.state)) setCreatorStudioPromptDraft('') } catch (error) { fail(error, '生成流程启动失败') } finally { setBusy((state: any) => ({ ...state, runningCreatorStudioDefaultFlow: false })); await refresh() } }
  const onRunSetup = async (id: string, setupId: string) => { setBusy((state: any) => ({ ...state, runningSetup: `${id}:${setupId}` })); try { await pluginHttpApi.setup(id, setupId); setStatus('Setup completed') } catch (error) { fail(error, 'Setup failed') } finally { setBusy((state: any) => ({ ...state, runningSetup: '' })); await refresh() } }
  const onOpenDashboard = async (id: string, dashboardId: string, options?: PluginDashboardOpenOptions) => { setBusy((state: any) => ({ ...state, openingDashboard: `${id}:${dashboardId}` })); try { const readiness = id === CREATOR ? await ensureCreatorStudioServiceReady({ api, pluginId: id, serviceId: 'studio', serviceStatus: serviceStatus(find(plugins, id)), onProgress: setStatus }) : null; await api.openPluginDashboard(id, dashboardId, options); setStatus(readiness?.started ? 'Creator Studio Service 已启动，Dashboard 已打开' : id === 'openpet.agent-awareness' && options?.query?.view === 'details' ? 'Codex 详情已打开' : 'Dashboard 已打开') } catch (error) { fail(error, 'Dashboard 打开失败') } finally { setBusy((state: any) => ({ ...state, openingDashboard: '' })); await refresh() } }
  const service = async (id: string, serviceId: string, operation: 'start' | 'stop' | 'health') => { const key = `${id}:${serviceId}`; setBusy((state: any) => ({ ...state, [operation === 'health' ? 'checkingServiceHealth' : 'changingService']: key })); try { const result = await pluginHttpApi.service(id, serviceId, operation); setStatus(operation === 'health' ? `Service health ${result.health?.status || 'checked'}` : operation === 'start' ? 'Service 已启动' : 'Service 已停止') } catch (error) { fail(error, `Service ${operation} failed`) } finally { setBusy((state: any) => ({ ...state, checkingServiceHealth: '', changingService: '' })); await refresh() } }
  const onSaveServiceHealthPolicy = async (id: string, serviceId: string, enabled: boolean, intervalMs: number) => { const key = `${id}:${serviceId}`; setBusy((state: any) => ({ ...state, savingServiceHealthPolicy: key })); try { await pluginHttpApi.servicePolicy(id, serviceId, { enabled, intervalMs }); setStatus(enabled ? 'Periodic health 已启用' : 'Periodic health 已停用') } catch (error) { fail(error, 'Periodic health policy failed') } finally { setBusy((state: any) => ({ ...state, savingServiceHealthPolicy: '' })); await refresh() } }
  const onExportLogs = async (format: 'json' | 'csv') => { try { const text = await pluginHttpApi.exportLogs({ ...filters, format }); downloadTextFile(`openpet-plugin-logs.${format}`, text, format === 'csv' ? 'text/csv;charset=utf-8' : 'application/json;charset=utf-8'); setStatus('日志已导出') } catch (error) { fail(error, '日志导出失败') } }
  const onClearLogs = async () => { try { await pluginHttpApi.clearLogs(); await loadLogsPage(filters, 1) } catch (error) { fail(error, '日志清空失败') } }
  const onClearStorage = async (id: string) => { if (!window.confirm(`清理插件 ${id} 的私有存储？`)) return; setBusy((state: any) => ({ ...state, clearingStorage: id })); try { await pluginHttpApi.storage(id); setStatus('插件存储已清理') } catch (error) { fail(error, '插件存储清理失败') } finally { setBusy((state: any) => ({ ...state, clearingStorage: '' })); await refresh() } }
  const onSaveImGatewayTelegramBotToken = async () => { const token = data.imGatewayTelegramTokenDraft.trim(); if (!token) return setStatus('Telegram Bot Token is required'); setBusy((state: any) => ({ ...state, savingImGatewayTelegramToken: true })); try { data.setImGatewaySecretState(await pluginHttpApi.imSecret('save', token)); setImGatewayTelegramTokenDraft(''); setStatus('Telegram token saved') } catch (error) { fail(error, 'Telegram token save failed') } finally { setBusy((state: any) => ({ ...state, savingImGatewayTelegramToken: false })); await refreshLogs() } }
  const onClearImGatewayTelegramBotToken = async () => { setBusy((state: any) => ({ ...state, clearingImGatewayTelegramToken: true })); try { data.setImGatewaySecretState(await pluginHttpApi.imSecret('clear')); setImGatewayTelegramTokenDraft(''); setStatus('Telegram token cleared') } catch (error) { fail(error, 'Telegram token clear failed') } finally { setBusy((state: any) => ({ ...state, clearingImGatewayTelegramToken: false })); await refreshLogs() } }
  return { onToggle, onSetNativeExecutionApproved, onInspectPluginPackage, onInspectGithubPluginRepository, onInstallReviewedPlugin, onUninstallPlugin, onSaveConfig, onRun, onRunCreatorStudioDefaultFlow, onRunSetup, onOpenDashboard, onStartService: (id: string, serviceId: string) => service(id, serviceId, 'start'), onStopService: (id: string, serviceId: string) => service(id, serviceId, 'stop'), onCheckServiceHealth: (id: string, serviceId: string) => service(id, serviceId, 'health'), onSaveServiceHealthPolicy, onExportLogs, onClearLogs, onClearStorage, onSaveImGatewayTelegramBotToken, onClearImGatewayTelegramBotToken }
}
